### ISSUE TITLE
button

### ISSUE THREAD

**Issue by egon1980** [FaqT0tum/Orbion_Space_Mouse#1]
when i push the button nothing happens. i'm a new bee in arduino. I ordered the exact parts that where in the list and checked the wiring multply times

**Comment by FaqT0tum** [comment]
have you configured the rear key in the oled display menu?

**Comment by egon1980** [comment]
i can't come in the menu

**Comment by FaqT0tum** [comment]
because?

**Comment by egon1980** [comment]
i don't why i can't access the menu

**Comment by egon1980** [comment]
i found the problem i didn't see there was a button x y axis

**Comment by FaqT0tum** [comment]
> 

ah, ok ... I close the discussion with a problem solved
