### ISSUE TITLE
V2 Step file missing?

### ISSUE THREAD

**Issue by mini-ninja-64** [FaqT0tum/Orbion_Space_Mouse#11]
Hello!

I noticed that the Orbion V2 has released and was very excited, but noticed that the step file was not available for V2 yet.

Will this be available soon?

**Comment by FaqT0tum** [comment]
forgive me, I thought I uploaded them.  give me time and I'll load them

**Comment by mini-ninja-64** [comment]
No need to apologize, thank you so much for your work on this its brilliant! ❤️
