### ISSUE TITLE
Arduino firmware upload issue

### ISSUE THREAD

**Issue by gti1984** [FaqT0tum/Orbion_Space_Mouse#13]
Hello and first thanks for your work.

I'm new in Arduino world and i have an issue.
I bought the Leonardo Pro Mini from your link but have this message when uploading the firmware.

Could you help me ?

Thanks
![image](https://user-images.githubusercontent.com/37384843/150569954-32f55b3e-3f62-405d-8d9d-e876f85f04f3.png)

**Comment by FaqT0tum** [comment]
Before starting I suggest you watch some videos on arduino, your problem seems to be the incorrect serial port.

![image](https://user-images.githubusercontent.com/69204222/150622422-84836ae2-1a3d-476e-b581-06a70373f52f.png)
