### ISSUE TITLE
axes wrong

### ISSUE THREAD

**Issue by kzipp89** [FaqT0tum/Orbion_Space_Mouse#15]
Hi. 
it looks like my axles are upside down. if I press up, it moves to the right. below = left left = below right = up. at which points in the code can I adjust this?

Ok i found. And work. Sry... 

U made nice job.

**Comment by Clay2F** [comment]
/////////////// JoyStick ///////////////////

int horzPin = A2;         // Pin Analog output of X        <------------
int vertPin = A1 ;        // Pin Analog output of Y        <------------
int joyButt = 15;         // Pin Joystick Button           <------------


Here you must Change the horzPin number nas the vertPin number

**Comment by FaqT0tum** [comment]
Problem solved
