### ISSUE TITLE
Not Recognised

### ISSUE THREAD

**Issue by Aesavyx** [FaqT0tum/Orbion_Space_Mouse#16]
After flashing the firmware, the pc calls the device "Unknown USB Device" in device manager and it no longer shows on the COM ports. The screen works but it doesn't do anything in any programs.

**Comment by Clay2F** [comment]
What program did you use to create the sketch?
I created mine with VScode and PlatformIO and had to add the libraries manually or use others.

**Comment by Aesavyx** [comment]
I used arduino IDE.

**Comment by FaqT0tum** [comment]
> Ho usato arduino IDE.

the problem has been solved?

**Comment by Aesavyx** [comment]
I think I just had a faulty pro micro

**Comment by drakengard780** [comment]
Same problem . After flash code.not recognize . I can t reflash

**Comment by edifabio-72** [comment]
Something similar happened to me too. I solved it by disconnecting and reconnecting the usb cable. The arduino board should change usb port. It should now reflash correctly.

**Comment by drakengard780** [comment]
When i write code , After thise the USB no recognized . So not work . What can i do ( sto perdendo la capa 😂)
