### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by bibine44** [FaqT0tum/Orbion_Space_Mouse#17]
salut
lorsque je tourne le scroll vers la droite cela dezoom et je voudrai faire l'inverse 
vers la droite = zoom
vers la gauche = dezoom

**Comment by FaqT0tum** [comment]
![image](https://user-images.githubusercontent.com/69204222/151679670-6c75999c-04ab-4cba-ba5c-a3cae98fd3b7.png)

Please write in English to facilitate other users reading the issue ... You can reverse the direction of rotation from the sketch

**Comment by FaqT0tum** [comment]
to the variable Mouse.move (0, 0, 1); the third number concerns the scroll, insert the minus sign where it is not and delete where it is, so as to reverse the rotation of the encoder
