### ISSUE TITLE
Rosters encoder needs more clearance

### ISSUE THREAD

**Issue by spuder** [FaqT0tum/Orbion_Space_Mouse#18]
The rotary encoder I received has solder that slightly interferes with the print

It would be good to add a little more clearance for resistors and solder joints

![image](https://user-images.githubusercontent.com/242382/151675540-8fc11833-280a-446a-b59d-64d3120f7641.jpeg)

**Comment by spuder** [comment]
I printed the 14 mm version from version 2.1 and the holes are also not aligned.

![image](https://user-images.githubusercontent.com/242382/151676526-26f16f84-aa20-40d8-a47a-75a4b8a77355.jpeg)

![image](https://user-images.githubusercontent.com/242382/151676531-d5535842-6fca-423b-be7b-4f61a38ab906.jpeg)

**Comment by Clay2F** [comment]
turn the printed part.
the hooks at the sides must show to the bottom

**Comment by Clay2F** [comment]
![D6D9E4FE-306B-4DF9-BC17-0DE4209DF315](https://user-images.githubusercontent.com/98338384/151677243-95610c79-48f8-4f5c-a576-6e0f461a228a.jpeg)

**Comment by spuder** [comment]
![image](https://user-images.githubusercontent.com/242382/151681352-fbf82eeb-ce14-477f-9f02-f106a74fd948.jpeg)

Thanks for the info. I've flipped the part and I'm finding that the holes still don't line up. I've drilled them out and trimmed excess material but it still isn't quite lined up.
