### ISSUE TITLE
Knob is too short

### ISSUE THREAD

**Issue by spuder** [FaqT0tum/Orbion_Space_Mouse#20]
I printed the 2.1 knob (short) and plate, but I'm finding the following problems

1. The pieces do not align
2. The Encoder is too short (I bought the exact one linked in the readme.

Did I print the wrong part? Or am I missing a piece?

![image](https://user-images.githubusercontent.com/242382/151685452-8cbbb536-5e5a-4433-8425-64d923a5ae79.jpeg)

![image](https://user-images.githubusercontent.com/242382/151685454-5234d8ac-1fba-4168-8ad8-29fbf950b7d3.jpeg)

![image](https://user-images.githubusercontent.com/242382/151685456-d387d5b0-88ad-4ef5-b128-a2f3f4560c5b.jpeg)

![image](https://user-images.githubusercontent.com/242382/151685460-4f76f4d6-aa93-40e9-a4a7-2bac33d56df5.jpeg)

**Comment by spuder** [comment]
The knob is assumed to be 27.6 mm tall, but the part referenced in the readme are only 23mm tall

![image](https://user-images.githubusercontent.com/242382/151685955-aa015b54-ba23-461c-9b63-f0ce389157b8.png)

**Comment by FaqT0tum** [comment]
the components in question are of low quality so even if the links are correct it may happen to receive parts with different tolerances!  therefore you can very well understand that I cannot create different components for each tolerance that the Chinese are wrong in production… there are many people who testify that the project quotas are correct, except in these cases like yours.  so please do not create a thousand issues Tricket for all your difficulties regarding the components ... Forgive me but unfortunately I am powerless in these cases

**Comment by jerzytuleja** [comment]
The problem is that Chinese producers offer KY-040 with long (with and without threads) and short shafts, with the same name of the product. 
I needed to buy 3 sets to get a proper one. I think the solution proposed by @spuder will solve the problem.

**Comment by AFUDIrk** [comment]
The encoder with the long thread is better.  This can also be fastened with
the nut.  Thus, the soldering points are not so heavily loaded.  Here's my
version.  https://github.com/AFUDIrk/Orbion_Space_Mouse-2.2

Mit freundlichen Grüßen
Dirk König

Jerzy Tuleja ***@***.***> schrieb am Fr., 4. Feb. 2022, 15:59:

**Comment by FaqT0tum** [comment]
> The problem is that Chinese producers offer KY-040 with long (with and without threads) and short shafts, with the same name of the product. I needed to buy 3 sets to get a proper one. I think the solution proposed by @spuder will solve the problem.

I am looking for a simple and universal solution
