### ISSUE TITLE
Can I use the regular mouse and your 3d mouse at the same time

### ISSUE THREAD

**Issue by wprojects** [FaqT0tum/Orbion_Space_Mouse#25]
My friend mentioned this mouse is emulated and fusion 360 can only use a single mouse at one time. His concern is that we wouldn't be able to use the 3d mouse while using our regular mouse at the same time. Is it possible to use both orion and a regular mouse simultaneously in fusion 360? Is the mouse emulated or connected like a real mouse? Also do I need to install a driver in linux or windows to get it to work?

**Comment by FaqT0tum** [comment]
Orbion uses the Mouse and keyboard libraries, therefore it is possible to use them together without problems as everyone does, obviously if you are doing Orbit and Pan you cannot use the mouse and vice versa. No, there is no need for any driver for any device, the orbion is recognized as a generic mouse and keyboard, you can also use it with smatphones and tablets
