### ISSUE TITLE
Freecad mode issue

### ISSUE THREAD

**Issue by piero78** [FaqT0tum/Orbion_Space_Mouse#26]
Hi,
the Freecad mode do not release after pan/orbit. Adding Mouse.release(MOUSE_RIGHT) solve the issue

**Comment by FaqT0tum** [comment]
> Hi, the Freecad mode do not release after pan/orbit. Adding Mouse.release(MOUSE_RIGHT) solve the issue

Thanks for reporting it, I fixed the problem with version 0.26.1

**Comment by piero78** [comment]
BTW, wonderful project, congratulazioni!
Buon lavoro
