### ISSUE TITLE
OLED stays dark

### ISSUE THREAD

**Issue by Davery92** [FaqT0tum/Orbion_Space_Mouse#27]
Good Morning, I've been following your project for a while and finally got all the parts necessary. I breadboarded everything this morning and uploaded the sketch after following your wiring schematic, but the OLED stays dark. I've tried two different screens and neither will turn on. The screen will randomly move due to having the joystick at an angle so I know something's wired right and working. Has this ever happened to you?

**Comment by FaqT0tum** [comment]
> Good Morning, I've been following your project for a while and finally got all the parts necessary. I breadboarded everything this morning and uploaded the sketch after following your wiring schematic, but the OLED stays dark. I've tried two different screens and neither will turn on. The screen will randomly move due to having the joystick at an angle so I know something's wired right and working. Has this ever happened to you?

the problem can be associated either with the wrong protocol, as there are identical OLEDs but with different controllers (SH1106 and SSD1306) or by the SDA and SCL cables reversed

**Comment by Somebody1566** [comment]
Hey Davery, this is common with breadboards and oleds. It will most likely work if you solder it. Same issue happened to me.

**Comment by Davery92** [comment]
You were absolutely right. I discovered this late last night while troubleshooting. I'll be soldering everything this week thanks for the help!

**Comment by Somebody1566** [comment]
No worries! Happy to help

**Comment by FaqT0tum** [comment]
> You were absolutely right. I discovered this late last night while troubleshooting. I'll be soldering everything this week thanks for the help!

If you need more help, I'll be happy to help you on Discord
