### ISSUE TITLE
unable to compile.. multiple errors in the icon.h file

### ISSUE THREAD

**Issue by tnap1979** [FaqT0tum/Orbion_Space_Mouse#31]
built 2.2, all parts assembled, all libraries installed, icon.h and ino in same folder...
go to verify or compile, and always this /302 error

**Comment by FaqT0tum** [comment]
> built 2.2, all parts assembled, all libraries installed, icon.h and ino in same folder... go to verify or compile, and always this /302 error

Log in to Discord so both me and others can help you in the best possible way ... as soon as you log in, share some screenshots in the Help section of Orbion
