### ISSUE TITLE
'Mouse' not found.

### ISSUE THREAD

**Issue by Cagedconner** [FaqT0tum/Orbion_Space_Mouse#32]
Arduino: 1.8.19 (Windows 10), Board: "Arduino Nano, ATmega328P"

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:8:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SSD1306/Adafruit_SSD1306.h:63:0: warning: "BLACK" redefined

 #define BLACK SSD1306_BLACK     ///< Draw 'off' pixels

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:1:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SH1106/Adafruit_SH1106.h:48:0: note: this is the location of the previous definition

 #define BLACK 0

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:8:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SSD1306/Adafruit_SSD1306.h:64:0: warning: "WHITE" redefined

 #define WHITE SSD1306_WHITE     ///< Draw 'on' pixels

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:1:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SH1106/Adafruit_SH1106.h:49:0: note: this is the location of the previous definition

 #define WHITE 1

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:8:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SSD1306/Adafruit_SSD1306.h:65:0: warning: "INVERSE" redefined

 #define INVERSE SSD1306_INVERSE ///< Invert pixels

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:1:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SH1106/Adafruit_SH1106.h:50:0: note: this is the location of the previous definition

 #define INVERSE 2

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:26:0:

C:\Program Files (x86)\Arduino\libraries\Mouse\src/Mouse.h:29:2: warning: #warning "Using legacy HID core (non pluggable)" [-Wcpp]

 #warning "Using legacy HID core (non pluggable)"

  ^~~~~~~

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:27:0:

C:\Program Files (x86)\Arduino\libraries\Keyboard\src/Keyboard.h:29:2: warning: #warning "Using legacy HID core (non pluggable)" [-Wcpp]

 #warning "Using legacy HID core (non pluggable)"

  ^~~~~~~

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:30:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SH1106/Adafruit_SH1106.h:48:0: warning: "BLACK" redefined

 #define BLACK 0

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:8:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SSD1306/Adafruit_SSD1306.h:63:0: note: this is the location of the previous definition

 #define BLACK SSD1306_BLACK     ///< Draw 'off' pixels

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:30:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SH1106/Adafruit_SH1106.h:49:0: warning: "WHITE" redefined

 #define WHITE 1

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:8:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SSD1306/Adafruit_SSD1306.h:64:0: note: this is the location of the previous definition

 #define WHITE SSD1306_WHITE     ///< Draw 'on' pixels

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:30:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SH1106/Adafruit_SH1106.h:50:0: warning: "INVERSE" redefined

 #define INVERSE 2

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:8:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SSD1306/Adafruit_SSD1306.h:65:0: note: this is the location of the previous definition

 #define INVERSE SSD1306_INVERSE ///< Invert pixels

 

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:30:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SH1106/Adafruit_SH1106.h:141:7: error: redefinition of 'class Adafruit_SH1106'

 class Adafruit_SH1106 : public Adafruit_GFX {

       ^~~~~~~~~~~~~~~

In file included from D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:1:0:

C:\Users\Conner\Documents\Arduino\libraries\Adafruit_SH1106/Adafruit_SH1106.h:141:7: note: previous definition of 'class Adafruit_SH1106'

 class Adafruit_SH1106 : public Adafruit_GFX {

       ^~~~~~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino: In function 'void setup()':

Orbion_FW_v0.26.2:109:5: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

     Mouse.begin();

     ^~~~~

Orbion_FW_v0.26.2:110:5: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

     Keyboard.begin();

     ^~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino: In function 'void loop()':

Orbion_FW_v0.26.2:136:15: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

               Keyboard.press(KEY_LEFT_ALT);

               ^~~~~~~~

Orbion_FW_v0.26.2:136:30: error: 'KEY_LEFT_ALT' was not declared in this scope

               Keyboard.press(KEY_LEFT_ALT);

                              ^~~~~~~~~~~~

Orbion_FW_v0.26.2:138:9: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

         Mouse.move(0, 0, -1);

         ^~~~~

Orbion_FW_v0.26.2:144:15: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

               Keyboard.press(KEY_LEFT_ALT);

               ^~~~~~~~

Orbion_FW_v0.26.2:144:30: error: 'KEY_LEFT_ALT' was not declared in this scope

               Keyboard.press(KEY_LEFT_ALT);

                              ^~~~~~~~~~~~

Orbion_FW_v0.26.2:146:11: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

           Mouse.move(0, 0, 1);

           ^~~~~

Orbion_FW_v0.26.2:158:11: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

           Keyboard.press(arButt [EEPROM.read(20)]);

           ^~~~~~~~

Orbion_FW_v0.26.2:173:11: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

           Mouse.release(MOUSE_MIDDLE);

           ^~~~~

Orbion_FW_v0.26.2:173:25: error: 'MOUSE_MIDDLE' was not declared in this scope

           Mouse.release(MOUSE_MIDDLE);

                         ^~~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:173:25: note: suggested alternative: 'MOUSE_h'

           Mouse.release(MOUSE_MIDDLE);

                         ^~~~~~~~~~~~

                         MOUSE_h

Orbion_FW_v0.26.2:174:11: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

           Keyboard.releaseAll();

           ^~~~~~~~

Orbion_FW_v0.26.2:185:11: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

           Keyboard.press(arButt [EEPROM.read(30)]);

           ^~~~~~~~

Orbion_FW_v0.26.2:200:11: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

           Mouse.release(MOUSE_MIDDLE);

           ^~~~~

Orbion_FW_v0.26.2:200:25: error: 'MOUSE_MIDDLE' was not declared in this scope

           Mouse.release(MOUSE_MIDDLE);

                         ^~~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:200:25: note: suggested alternative: 'MOUSE_h'

           Mouse.release(MOUSE_MIDDLE);

                         ^~~~~~~~~~~~

                         MOUSE_h

Orbion_FW_v0.26.2:201:11: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

           Keyboard.releaseAll();

           ^~~~~~~~

Orbion_FW_v0.26.2:222:11: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

           Mouse.move(0, (invertMouseY * (YValue / sens)), 0);

           ^~~~~

Orbion_FW_v0.26.2:229:11: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

           Mouse.move((invertMouseX * (XValue / sens)), 0, 0);

           ^~~~~

Orbion_FW_v0.26.2:237:15: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

               Keyboard.releaseAll();

               ^~~~~~~~

Orbion_FW_v0.26.2:242:19: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

                   Mouse.release(MOUSE_MIDDLE);

                   ^~~~~

Orbion_FW_v0.26.2:242:33: error: 'MOUSE_MIDDLE' was not declared in this scope

                   Mouse.release(MOUSE_MIDDLE);

                                 ^~~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:242:33: note: suggested alternative: 'MOUSE_h'

                   Mouse.release(MOUSE_MIDDLE);

                                 ^~~~~~~~~~~~

                                 MOUSE_h

Orbion_FW_v0.26.2:243:33: error: 'MOUSE_LEFT' was not declared in this scope

                   Mouse.release(MOUSE_LEFT);

                                 ^~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:243:33: note: suggested alternative: 'MOUSE_h'

                   Mouse.release(MOUSE_LEFT);

                                 ^~~~~~~~~~

                                 MOUSE_h

Orbion_FW_v0.26.2:244:33: error: 'MOUSE_RIGHT' was not declared in this scope

                   Mouse.release(MOUSE_RIGHT);

                                 ^~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:244:33: note: suggested alternative: 'MOUSE_h'

                   Mouse.release(MOUSE_RIGHT);

                                 ^~~~~~~~~~~

                                 MOUSE_h

Orbion_FW_v0.26.2:262:7: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

       Keyboard.releaseAll();

       ^~~~~~~~

Orbion_FW_v0.26.2:263:7: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

       Mouse.release(MOUSE_MIDDLE);

       ^~~~~

Orbion_FW_v0.26.2:263:21: error: 'MOUSE_MIDDLE' was not declared in this scope

       Mouse.release(MOUSE_MIDDLE);

                     ^~~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:263:21: note: suggested alternative: 'MOUSE_h'

       Mouse.release(MOUSE_MIDDLE);

                     ^~~~~~~~~~~~

                     MOUSE_h

Orbion_FW_v0.26.2:264:21: error: 'MOUSE_LEFT' was not declared in this scope

       Mouse.release(MOUSE_LEFT);

                     ^~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:264:21: note: suggested alternative: 'MOUSE_h'

       Mouse.release(MOUSE_LEFT);

                     ^~~~~~~~~~

                     MOUSE_h

Orbion_FW_v0.26.2:265:21: error: 'MOUSE_RIGHT' was not declared in this scope

       Mouse.release(MOUSE_RIGHT);

                     ^~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:265:21: note: suggested alternative: 'MOUSE_h'

       Mouse.release(MOUSE_RIGHT);

                     ^~~~~~~~~~~

                     MOUSE_h

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino: In function 'void selModes()':

Orbion_FW_v0.26.2:493:9: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

         Keyboard.press(KEY_LEFT_SHIFT);

         ^~~~~~~~

Orbion_FW_v0.26.2:493:24: error: 'KEY_LEFT_SHIFT' was not declared in this scope

         Keyboard.press(KEY_LEFT_SHIFT);

                        ^~~~~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:493:24: note: suggested alternative: 'PIN_MODE_SHIFT'

         Keyboard.press(KEY_LEFT_SHIFT);

                        ^~~~~~~~~~~~~~

                        PIN_MODE_SHIFT

Orbion_FW_v0.26.2:494:9: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

         Mouse.press(MOUSE_MIDDLE);

         ^~~~~

Orbion_FW_v0.26.2:494:21: error: 'MOUSE_MIDDLE' was not declared in this scope

         Mouse.press(MOUSE_MIDDLE);

                     ^~~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:494:21: note: suggested alternative: 'MOUSE_h'

         Mouse.press(MOUSE_MIDDLE);

                     ^~~~~~~~~~~~

                     MOUSE_h

Orbion_FW_v0.26.2:505:24: error: 'KEY_LEFT_ALT' was not declared in this scope

         Keyboard.press(KEY_LEFT_ALT);

                        ^~~~~~~~~~~~

Orbion_FW_v0.26.2:512:21: error: 'MOUSE_LEFT' was not declared in this scope

         Mouse.press(MOUSE_LEFT);

                     ^~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:512:21: note: suggested alternative: 'MOUSE_h'

         Mouse.press(MOUSE_LEFT);

                     ^~~~~~~~~~

                     MOUSE_h

Orbion_FW_v0.26.2:518:21: error: 'MOUSE_RIGHT' was not declared in this scope

         Mouse.press(MOUSE_RIGHT);

                     ^~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:518:21: note: suggested alternative: 'MOUSE_h'

         Mouse.press(MOUSE_RIGHT);

                     ^~~~~~~~~~~

                     MOUSE_h

Orbion_FW_v0.26.2:533:24: error: 'KEY_LEFT_CTRL' was not declared in this scope

         Keyboard.press(KEY_LEFT_CTRL);

                        ^~~~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino: In function 'void selButt(int*)':

Orbion_FW_v0.26.2:661:11: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

           Keyboard.press(32);

           ^~~~~~~~

Orbion_FW_v0.26.2:665:26: error: 'KEY_LEFT_CTRL' was not declared in this scope

           Keyboard.press(KEY_LEFT_CTRL);

                          ^~~~~~~~~~~~~

Orbion_FW_v0.26.2:669:26: error: 'KEY_LEFT_SHIFT' was not declared in this scope

           Keyboard.press(KEY_LEFT_SHIFT);

                          ^~~~~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:669:26: note: suggested alternative: 'PIN_MODE_SHIFT'

           Keyboard.press(KEY_LEFT_SHIFT);

                          ^~~~~~~~~~~~~~

                          PIN_MODE_SHIFT

Orbion_FW_v0.26.2:673:26: error: 'KEY_LEFT_ALT' was not declared in this scope

           Keyboard.press(KEY_LEFT_ALT);

                          ^~~~~~~~~~~~

Orbion_FW_v0.26.2:677:26: error: 'KEY_TAB' was not declared in this scope

           Keyboard.press(KEY_TAB);

                          ^~~~~~~

Orbion_FW_v0.26.2:681:26: error: 'KEY_ESC' was not declared in this scope

           Keyboard.press(KEY_ESC);

                          ^~~~~~~

Orbion_FW_v0.26.2:685:26: error: 'KEY_DELETE' was not declared in this scope

           Keyboard.press(KEY_DELETE);

                          ^~~~~~~~~~

Orbion_FW_v0.26.2:689:11: error: 'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

           Mouse.press(MOUSE_MIDDLE);

           ^~~~~

Orbion_FW_v0.26.2:689:23: error: 'MOUSE_MIDDLE' was not declared in this scope

           Mouse.press(MOUSE_MIDDLE);

                       ^~~~~~~~~~~~

D:\Downloads\Orbion_Space_Mouse-main (1)\Orbion_Space_Mouse-main\Orbion_Firmware\Orbion_FW_v0.26.2\Orbion_FW_v0.26.2.ino:689:23: note: suggested alternative: 'MOUSE_h'

           Mouse.press(MOUSE_MIDDLE);

                       ^~~~~~~~~~~~

                       MOUSE_h

Orbion_FW_v0.26.2:693:26: error: 'KEY_LEFT_GUI' was not declared in this scope

           Keyboard.press(KEY_LEFT_GUI);

                          ^~~~~~~~~~~~

exit status 1

'Mouse' not found. Does your sketch include the line '#include <Mouse.h>'?

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

 new arduino user here, likely user error but have tried a few things now and still get this error, even though that line is obviously present in the code

**Comment by edifabio-72** [comment]
The microprocessor ATmega328P do not support mouse and keyboard library. It is essential to use ARDUINO PRO MICRO with ATMEL32U4 processor.

**Comment by FaqT0tum** [comment]
have you read the guide carefully?  have you read all the disclaimes?  if you need more assistance go to Discord, you will find all the help you need https://discord.gg/KAbUJ2Gr

**Comment by Cagedconner** [comment]
Thank you for the quick response, I must have received a different model arduino with my parts order. I assumed my "leonardo" was a pro micro from the store description
