### ISSUE TITLE
Manual?

### ISSUE THREAD

**Issue by Sisko4** [FaqT0tum/Orbion_Space_Mouse#34]
Is there anywhere a manual that describes what screws go where and also what parts need the insert nuts?
Anything other is absolute clear for me.
Thanks :-)

**Comment by Sisko4** [comment]
> If you are able to view the CAD within this repository, using Fusion 360 you can see the inserts in there. In addition, can always join the Discord group @FaqT0tum set up, there's plenty of us who can give you help.

Well...the easy solutions are never available in my own brain^^
Thank you very much!

**Comment by Roycinger** [comment]
> 
you might close the issue to maintain overview :)
