### ISSUE TITLE
Screen Cover need a little change to prevent screen cracking during install

### ISSUE THREAD

**Issue by blaghislain** [FaqT0tum/Orbion_Space_Mouse#35]
I wasn't able to install Oled inside screen cover with having it to crack because a portion of plastic (see red part on image) push to much pressure on screen.  After few tries I had to change the STL.

Here (in red) the section that need to be removed
![2022-02-15_10-00-51](https://user-images.githubusercontent.com/19159135/154088695-ed0fe7c8-41dd-40fb-ad98-c6a39d863661.jpg)

Thanks in advance

**Comment by FaqT0tum** [comment]
how many mm are there (red part)?

**Comment by blaghislain** [comment]
Here are the mesurement
![2022-02-15_14-36-22](https://user-images.githubusercontent.com/19159135/154136484-0ea85827-c6dc-4a8e-a1ec-263284608bc3.jpg)
![2022-02-15_14-36-59](https://user-images.githubusercontent.com/19159135/154136516-8fe69840-8ae3-4f12-b400-cb053e956bd5.jpg)
![2022-02-15_14-37-47](https://user-images.githubusercontent.com/19159135/154136550-0826e6f7-c786-4e86-85e7-00007824ff7b.jpg)
![2022-02-15_14-38-36](https://user-images.githubusercontent.com/19159135/154136560-cf127a3c-5647-450c-b7e8-473cfaa5fa5c.jpg)
![2022-02-15_14-39-53](https://user-images.githubusercontent.com/19159135/154136583-d146673e-2447-487c-b366-b54a64d41271.jpg)
![2022-02-15_14-40-20](https://user-images.githubusercontent.com/19159135/154136591-ceb6e9f8-3d86-4547-aeef-6db79a3a1df1.jpg)
Thanks in advance

**Comment by FaqT0tum** [comment]
Thank you!  tomorrow afternoon I'll make the change ... now I'm at work until tomorrow 😅

**Comment by FaqT0tum** [comment]
I updated the cads with these changes suggested by you, but I haven't published them yet, for other changes to be made ... thanks again

**Comment by Sisko4** [comment]
I have the same issue plus the pins don´t fit with the pcb.

**Comment by FaqT0tum** [comment]
I'm solving the problem by eliminating the pin method altogether!  if the printer leaves for the confirmation tests I publish the solution as soon as possible

**Comment by Sisko4** [comment]
I think the pins aren´t usefull at all, you can also glue the lower part to the base and solve it that way.
Disassembly shouldn´t be a problem that way also for the body.

**Comment by FaqT0tum** [comment]
![image](https://user-images.githubusercontent.com/69204222/156356808-3cfea624-d1f5-47aa-af79-fd6dbdebe464.jpeg)
