### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by JaY-III** [FaqT0tum/Orbion_Space_Mouse#38]
link found here:
https://github.com/FaqT0tum/Orbion_Space_Mouse/blob/main/README.md
https://discord.gg/3S2ZAGSf is expired 
please update, thanks

**Comment by FaqT0tum** [comment]
I have updated the link. forgive me, but I'm new to discord :P

**Comment by JaY-III** [comment]
Just a heads up, it's also expired on your other sites you have a link for it.On Feb. 16, 2022 16:16, FaqTotum ***@***.***> wrote:
I have updated the link. forgive me, but I'm new to discord :P
