### ISSUE TITLE
Specifiy what type of filament it is expected to be used

### ISSUE THREAD

**Issue by VinnyCordeiro** [FaqT0tum/Orbion_Space_Mouse#39]
I had fitment issues with all electronic components because I printed the parts in ABS, so that makes me conclude the STL files were made considering that they'll be printed in PLA. Please, specify that on the README.md file.

**Comment by VinnyCordeiro** [comment]
PLA have very low shrinkage rates, so you can basically print it as designed. For ABS you have to compensate the shrinkage effect, and that have to be made for each piece, because the shrinkage isn't linear. 😫

**Comment by FaqT0tum** [comment]
already, but it is something that you can fix using a slicer.  there is no need to make special files

**Comment by VinnyCordeiro** [comment]
Never asked for that, just a note concerning shrinkage of filaments other than PLA.

**Comment by FaqT0tum** [comment]
I'll make one in the READEM.md file… ☺️
