### ISSUE TITLE
Broken link for joystick

### ISSUE THREAD

**Issue by spuder** [FaqT0tum/Orbion_Space_Mouse#4]
Joystick (KY-023): https://s.click.aliexpress.com/e/_AM43rq2 (important: the joystick shaft must be 4mm)

This link is broken 

Here are a bunch of items with the name `ky-023` but I'm not sure what you mean by the shaft must be 4mm. None of these mention how long the joystick shaft is

https://www.aliexpress.com/af/joystcik-ky-023.html?d=y&origin=n&SearchText=joystcik+ky+023&catId=0&initiative_id=SB_20220109124741

Could you point out which one you would buy?

**Comment by FaqT0tum** [comment]
Thank you for reporting the issue. Now it's been fixed
