### ISSUE TITLE
Why such a restrictive license?

### ISSUE THREAD

**Issue by VinnyCordeiro** [FaqT0tum/Orbion_Space_Mouse#41]
Having contributed to some open projects, both on software and hardware, it makes me wonder why CC BY-NC-ND 4.0 was chosen. By the terms of the chosen license, I can't fork your repo, make changes, and then commiting those changes on my forked repo without violating it. That greatly stifles contributions from other people that could help enhance this project. Not to mention that all the libraries used on the firmware side are Open Source licenses (GPL v2 or LGPL v2.1 for Arduino libraries, 3-Clause BSD or MIT licenses for Adafruit libraries).

Please don't take that as anything else as an attempt to understand the license choice.

**Comment by FaqT0tum** [comment]
the license does not allow remixing, it was decided not to disperse the original project in 1000 forks or remixes on 1000 sites ... as has already been specified in the READEM.md file, you can always contribute to the improvement of the project which remains opensource, just communicate it and I insert it in the parent project.  the libraries I use are freely licensed, including commercial ones.  the project is open source and has not been limited in any way, but has only rules to respect that point only to improvement.  I for one do not ask for money and I dedicate time, renewable energy and investments for a common and not personal factor.  anyway I didn't take it, it's right to have doubts and ask 😋.  I hope I've been exhaustive.
