### ISSUE TITLE
Knob_Axis joystick connection improvements

### ISSUE THREAD

**Issue by mace-man** [FaqT0tum/Orbion_Space_Mouse#42]
Red -> PLA
Black -> TPU
![s-PXL_20220218_075845308](https://user-images.githubusercontent.com/79518216/154644786-ff5309e3-3156-428e-a8b0-2977294a49ba.jpg)
![s-PXL_20220218_080047996](https://user-images.githubusercontent.com/79518216/154644808-93bc6b0c-a038-4e23-bc0d-81e8e8e143cc.jpg)
The connection between the joystick and Knob_Axis has been improved.

**Comment by FaqT0tum** [comment]
having a flex material at that point does not improve movement but only facilitates the connection between the joystick and the base knob.  the connection must be as rigid as possible as the joystick already has some play

but it's a nice idea.  Well done.  if you want to participate in improving Orbion with lots of ideas, you can join the Discord (find the link on the main page)
