### ISSUE TITLE
Arduino Micro or Leonardo ?

### ISSUE THREAD

**Issue by fredmccr** [FaqT0tum/Orbion_Space_Mouse#45]
Hi,
I ordered and received my Arduino board from Aliexpress (same link as yours).
It's labeled "Pro Micro" on its top but when I get board info from Arduino IDE, it shows "Arduino Leonardo".
What kind of board should I select before flashing: "Arduino Micro" as stated in the readme file or "Arduino Leonardo" ?
Thanks

**Comment by kc0rpm** [comment]
Mine showed up as a Leonardo also. Select micro when uploading code though.

**Comment by fredmccr** [comment]
Thank you for your help.
I just flashed my board like you advised. Is it normal now that one of the two red LEDs remains always on ?

**Comment by kc0rpm** [comment]
Yeah, thats normal.

**Comment by Sisko4** [comment]
I think selecting it as Arduino Micro just briked it. It doesn´t finish uploading.

**Comment by Sisko4** [comment]
Does it make any difference anyway if you choose Micro or Leonardo?
Every seller writes you need to choose Leonardo in the Board Selection.

**Comment by kc0rpm** [comment]
I don't see why it would. Both boards use the same ATmega32U4 processor. The micro is just a miniaturized version. Of course I could be wrong.

**Comment by FaqT0tum** [comment]
the arduino pro micro is a miniaturized leonardo
