### ISSUE TITLE
What is that part on the Micro?

### ISSUE THREAD

**Issue by Sisko4** [FaqT0tum/Orbion_Space_Mouse#46]
I had to reset my Ardunio Micro because of an user error, after some searching i found out that that part is not the reset switch i first thought, but what is it then?
When i double tapped that chip a few times it looked for me like it resets because the LEDs light up in a certain order.
Could i have damaged that part maybe or is everything okay?

https://abload.de/img/partn8js0.jpg

**Comment by netweaver1970** [comment]
It's the external crystal oscillator, needed by the MCU for its proper working. Not a switch...
