### ISSUE TITLE
Recommended Cables

### ISSUE THREAD

**Issue by Sisko4** [FaqT0tum/Orbion_Space_Mouse#47]
What is the recommended AWG value for the cables?
I have some 30AWG / 0,6mm telephone cables here, but i think they might be to thin for this as they have only one strain (0,25mm), also go right trough the pins of the board.

My cables: https://de.aliexpress.com/i/1005001320739063.html

Amazon or Aliexpress link would be great!

Thanks :-)

**Comment by FaqT0tum** [comment]
I added the recommended cable with the link to the parts list.  I recommend a silicone 28awg

**Comment by Sisko4** [comment]
Thank you for the fast answer! :-)
