### ISSUE TITLE
cushion 3d model fails to print

### ISSUE THREAD

**Issue by wprojects** [FaqT0tum/Orbion_Space_Mouse#49]
[](https://github.com/FaqT0tum/Orbion_Space_Mouse/blob/main/Orbion_STL/Orbion_Rev2.2/Cushion_HiNATA.stl) This model fails to print no matter which direction I flip it. It even fails when I print it with supports. Does anyone have a version that  will print correctly or can explain to me why this is happening? I am printing in PETG and every other part has printed fine

**Comment by FaqT0tum** [comment]
there are many reasons why you can't, but not attributable to the model as we have all printed it without problems. I don't know why you mention PETG, but the cushion has to be molded in TPU

**Comment by wprojects** [comment]
@FaqT0tum so I have to print that part in TPU in order to get it to work?
