### ISSUE TITLE
Can I add RGB

### ISSUE THREAD

**Issue by Kretdiop** [FaqT0tum/Orbion_Space_Mouse#6]
Can I add RGB to this project if one PWM is used by OLED ?

**Comment by FaqT0tum** [comment]
explain yourself better, I didn't understand what you mean

**Comment by Kretdiop** [comment]
To connect RGB i need 3 free PWM and GND. But in Diagram i see only 2 free PWM

**Comment by FaqT0tum** [comment]
Use WS2812 LEDs, they only need 3 pins, GND 5V and one digital pin
