### ISSUE TITLE
Possible enhancement to include lateral input

### ISSUE THREAD

**Issue by Stargrove1** [FaqT0tum/Orbion_Space_Mouse#7]
Not an issue, just an idea I'd like to ask about.

Arduino has two free AIs, this would allow to add a second joystick input. If the second joystick gets mounted upside down on top of the existing one, it might be possible to create a lateral input by adding both joysticks absolute value for lateral movement, while adding the values for existing input. The joysticks need to be connected by a kind of tube, maybe printed and glued.
See below sketch
  
![image](https://user-images.githubusercontent.com/2905622/149967029-73cabd04-f28c-4968-9aef-87b392d4aea9.png)
![image](https://user-images.githubusercontent.com/2905622/149967135-7fb4b66a-0193-4026-adb6-004cf8b08ba1.png)

**Comment by FaqT0tum** [comment]
I like the idea, but in this way you would raise the knob too much, in addition to the fact that the movement will always be on a fulcrum and never linear

However, I am already working on a version with 6 axes managed by optical sensors which are the best choice for precision and reliability.

**Comment by Stargrove1** [comment]
You are right, it would require to lower it down in the base. The loss in height during lateral movement would be not be very big, only ~3mm. 

But if you are already working on a different solution, that's even better. What kind of optical sensor will be used?

**Comment by FaqT0tum** [comment]
3mm can be many.  for the optical sensor for now I can tell you a little, I am still looking for an optimal solution for the simplified realization and functionality

**Comment by Stargrove1** [comment]
I hope to see the upgrade soon. Thank you for your effort
