### ISSUE TITLE
Knob axis base mount (the thing you put on the joystick-shaft)

### ISSUE THREAD

**Issue by binxyde** [FaqT0tum/Orbion_Space_Mouse#9]
Hi there! 

You did an awesome job with this! I love your precise design an especially the fact that you only used modules that are available quick and easy! :)

The last days I rebuilt this cool space mouse, and I would like to suggest a little mod on the knob axis part.
I made the mount for the joystick-shaft 3mm longer and made a little bit more space for it inside. 0.2mm in every direction.
Then you can push it easily onto the joystick and you have a little bit space to calibrate the alignment to the base.
A drop of hot-glue will hold it tight.

With the original design I destroyed one of my joystick modules while trying to push it onto the shaft :/

Best wishes,
binxyde

![knob_axis_mod_1](https://user-images.githubusercontent.com/34035431/150129965-4d8d043e-a847-466b-8475-32174be67c39.jpg)
![knob_axis_mod_2](https://user-images.githubusercontent.com/34035431/150129966-9a01a0fe-621e-4acc-b499-13bf5f465b17.jpg)

**Comment by stevedee78** [comment]
Can you share the STL from your Knob_axis, please?

**Comment by FaqT0tum** [comment]
the holes are very dependent on the print quality, if the printer creates small blobs, internal seams or is not properly adjusted, the holes may be wider or narrower ... I assume this is your case as it is the only signal that has arrived.  all files have already been released in the STL section, including the REV.  2

**Comment by binxyde** [comment]
@FaqT0tum yeah...the printer (creality cr-10s pro) was calibrated just before that print...but i saw that i have forgotten to use your extrusion width parameters. maybe thats the fault.

@stevedee78 i can't attach stl files here. But FaqT0tum published the fusion file. so its an easy thing to mod it by yourself.
